layouts:
    - tall
    - fullscreen

mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

window-margins: false

# Hide "heads up display"
enables-layout-hud: false 
enables-layout-hud-on-space-change: false

# stop some windows from being effected by amethyst
floating: ["com.apple.systempreferences", "com.microsoft.teams"]
